%% Flux Optimization + Elastic Net Model Construction

% Note: code for flux optimization + elastic net model construction has
% some stochasticity in the results it generates. 

%% Initializing Cobra + Model
clear;

% initializes cobra toolbox
initCobraToolbox;
changeCobraSolver('gurobi');

%% Loads quiescence deepening transcriptomics
fujimaki_19 = readtable('fujimaki_19.txt');

% loads Rat-GEM metabolic model
load Rat-GEM.mat;
model = ratGEM;
model.b = model.b(:, 1);
model = generateRules(model);
model.genes = upper(model.genes);
  
%%
% Collecting gene lists for progressively deeper quiescence 

% isolates genes in model
fujimaki_19.Gene = upper(fujimaki_19.Gene);
fujimaki_19 = fujimaki_19(ismember(fujimaki_19.Gene, model.genes), :);

qds_flux = [3 3 3 4 4 4 6 6 6 8 8 8 10 10 10 12 12 12 14 14 14 16 16 16]';

%% Regression model + flux optimization

thresh_up = 1;
thresh_down = 1 / thresh_up;

up_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 > thresh_up)
        }

dw_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 < thresh_down)
        }


num_rxns = length(model.rxnNames);

% quiescence depth scores
qds_flux = [3 3 3 4 4 4 6 6 6 8 8 8 10 10 10 12 12 12 14 14 14 16 16 16]'


%% Optimizing kappa / rho / epsilon 
% (objective function biomass optimized, fc_thresh = 1)

weight_kr = []; weight_e = [];

weight_kr = logspace(-1, 4, 15)
weight_kr = repelem(weight_kr, 10)

weight_e = logspace(-3, -2, 10)
weight_e = repmat(weight_e, 1, 15)

mse_cv = [];

parfor k = 1:length(weight_kr)

    
    flux_q = zeros(length(up_q), length(model.rxnNames));

    kappa = weight_kr(k);
    rho = weight_kr(k);
    epsilon = weight_e(k);

    for i = 1:length(up_q)
    
        i;
        flux_q(i, :) = constrain_flux_regulation_inconsistencies(model, ...
                                                      up_q{i}, dw_q{i}, kappa, rho, epsilon, 0, [], 1);
        
    end
    
    
    % fitrlinear linear regression model to predict QDS based on fluxes 
    X_train = flux_q;
    Y_train = qds_flux;
    
    [B, FitInfo] = lasso(X_train, Y_train, 'Alpha', 0.1, 'CV', 3);
    
    idxLambdaMinMSE = FitInfo.IndexMinMSE;
    coef = B(:, idxLambdaMinMSE);
    coef0 = FitInfo.Intercept(idxLambdaMinMSE);
    
    % finds crossfold mse
    mse_cv(k) = FitInfo.MSE(idxLambdaMinMSE);


end

plot(1:150, mse_cv)
ylabel("mse cv")

[M, I] = min(mse_cv)
kappa_rho_min = weight_kr(I)
epsilon_min = weight_e(I)

kappa_rho_epsilon_table = table(weight_kr', weight_e', mse_cv', 'VariableNames', {'Kappa_Rho_Weight', 'Epsilon_Weight', 'Cross_validated_MSE'})


%% Optimizing objective function (kappa / rho / epsilon constant, 
% objective function optimized, fc_thresh = 1)

model_biomass = model

% change objective function to maximize nadh Rat-GEM
model_nadh = addExchangeRxn(model,{'MAM02553c'},0,100); % create a fake reaction to produce atp
model_nadh.c(find(model.c)) = 0; % set the biomass obj c value to 0
model_nadh.c(end) = 1; % maximize the last reaction i.e. atp production

% change objective function to maximize glutathione Rat-GEM
model_glut = addExchangeRxn(model,{'MAM02026c'},0,100); % create a fake reaction to produce atp
model_glut.c(find(model.c)) = 0; % set the biomass obj c value to 0
model_glut.c(end) = 1; % maximize the last reaction i.e. atp production

% change objective function to maximize ATP Rat-GEM
model_atp = addExchangeRxn(model,{'MAM01371c'},0,100); % create a fake reaction to produce atp
model_atp.c(find(model.c)) = 0; % set the biomass obj c value to 0
model_atp.c(end) = 1; % maximize the last reaction i.e. atp production


models = [model_biomass, model_nadh, model_glut, model_atp];

models_t = [models, models, models];
mse = [];
mse_cv = [];

parfor k = 1:length(models_t)

    
    model = models_t(k);
    flux_q = [];

    kappa = 372.7594
    rho = 372.7594
    epsilon = 0.0036


    for i = 1:length(up_q)
    
        flux_q(i, :) = constrain_flux_regulation_inconsistencies(model, ...
                                                      up_q{i}, dw_q{i}, kappa, rho, epsilon, 0, [], 1);
        
    end

    X_train = []; Y_train = [];


    X_train = flux_q;
    Y_train = qds_flux;
    
    [B, FitInfo] = lasso(X_train, Y_train, 'Alpha', 0.1, 'CV', 3);
    
    idxLambdaMinMSE = FitInfo.IndexMinMSE;
    coef = B(:, idxLambdaMinMSE);
    coef0 = FitInfo.Intercept(idxLambdaMinMSE);
    
    % finds crossfold mse
    mse_cv(k) = FitInfo.MSE(idxLambdaMinMSE);


end

mse_cv_avg = [mean([mse_cv(1), mse_cv(5), mse_cv(9)]), ...
              mean([mse_cv(2), mse_cv(6), mse_cv(10)]), ...
              mean([mse_cv(3), mse_cv(7), mse_cv(11)]), ...
              mean([mse_cv(4), mse_cv(8), mse_cv(12)]), ...            
              ];


model_types = [1 2 3 4];

plot(model_types, mse_cv_avg)
legend(["mse", "mse cv"])

[M, I] = min(mse_cv_avg);
types_min = model_types(I);

obj_func_table = table(["biomass", "nadh", "glutathione", "atp"]', mse_cv_avg', 'VariableNames', {'Objective_Function', 'Cross_validated_MSE_Avg'});


%% Optimizing fold change threshold (kappa / rho / epsilon constant, 
% biomass optimized)

model = ratGEM;
model.b = model.b(:, 1);
model = generateRules(model);
model.genes = upper(model.genes);

mse = [];
mse_cv = [];

fc_thresh_array = linspace(1, 1.2, 24);
fc_thresh_array = repelem(fc_thresh_array, 4);


parfor k = 1:length(fc_thresh_array)

    
    flux_q = [];

    kappa = 372.7594;
    rho = 372.7594;
    epsilon = 0.0036;

    thresh_up = fc_thresh_array(k);
    thresh_down = 1 / thresh_up;

    
    up_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
        fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 > thresh_up)
        };

     dw_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
        fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 < thresh_down)
        };


    for i = 1:length(up_q)
    
        % treatment
        flux_q(i, :) = constrain_flux_regulation_inconsistencies(model, ...
                                                      up_q{i}, dw_q{i}, kappa, rho, epsilon, 0, [], 1);
        
    end

    X_train = []; Y_train = [];


    X_train = flux_q;
    Y_train = qds_flux;
    
    % alpha of 0.1 chosen based on preliminary analyses showing it
    % minimizes CV MSE
    [B, FitInfo] = lasso(X_train, Y_train, 'Alpha', 0.1, 'CV', 3);
    
    idxLambdaMinMSE = FitInfo.IndexMinMSE;
    coef = B(:, idxLambdaMinMSE);
    coef0 = FitInfo.Intercept(idxLambdaMinMSE);
    
    % finds crossfold mse
    mse_cv(k) = FitInfo.MSE(idxLambdaMinMSE);


end

%% takes average of 4 replicates of mse
mse_cv_avg = [];

k = 1

for i = 1:4:96

    mse_cv_avg(k) = mean(mse_cv(i:(i+3)));

    k = k + 1;

end

fc_thresh_array = linspace(1, 1.2, 24);

plot(fc_thresh_array, mse_cv_avg);

[M, I] = min(mse_cv_avg);
fc_min = fc_thresh_array(I);



fc_table = table(fc_thresh_array', mse_cv_avg', 'VariableNames', {'Fold_Change_Threshold', 'Cross_validated_MSE_avg'})


%% Optimizing alpha (ratio of ridge to lasso) (kappa / rho / epsilon constant, 
% biomass optimized)

load Rat-GEM.mat
model = ratGEM;
model.b = model.b(:, 1);
model = generateRules(model);
model.genes = upper(model.genes);


flux_q = [];
kappa = 372.7594;
rho = 372.7594;
epsilon = 0.0036;

thresh_up = 1.008695652; 
thresh_down = 1 / thresh_up;


up_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 > thresh_up)
    }

 dw_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 < thresh_down)
    };


    parfor i = 1:length(up_q)
    
        flux_q(i, :) = constrain_flux_regulation_inconsistencies(model, ...
                                                      up_q{i}, dw_q{i}, kappa, rho, epsilon, 0, [], 1);
        
    end

%%

alpha_array = [];
alpha_array = logspace(-3, -0.01, 200);
alpha_array = repelem(alpha_array, 4);

mse_cv = [];
num_coeff = [];

X_train = []; Y_train = [];
X_train = flux_q;
Y_train = qds_flux;

parfor i = 1:length(alpha_array)

    
    B = []; FitInfo = [];

    [B, FitInfo] = lasso(X_train, Y_train, 'Alpha', alpha_array(i), 'CV', 3);

    idxLambdaMinMSE = FitInfo.IndexMinMSE;
    coef = B(:, idxLambdaMinMSE);
    
    % finds crossfold mse
    mse_cv(i) = FitInfo.MSE(idxLambdaMinMSE);
    num_coeff(i) = sum(coef ~= 0);

end

% takes average of 4 replicates of mse
mse_cv_avg = [];
num_coeff_avg = [];

k = 1;

for i = 1:4:800

    mse_cv_avg(k) = mean(mse_cv(i:(i+3)));
    num_coeff_avg(k) = mean(num_coeff(i:(i+3)));

    k = k + 1;

end

alpha_array = logspace(-3, -0.01, 200);

plotyy(log10(alpha_array), log(mse_cv_avg), log10(alpha_array), num_coeff_avg)
legend(["CV MSE", "Num Coeff"]);
xlabel("Alpha");

[M, I] = min(mse_cv_avg);

alpha_array(I)
num_coeff_avg(I)

alpha_table = table(alpha_array', num_coeff_avg', mse_cv_avg', 'VariableNames', {'Alpha', 'Num_coefficients_avg', 'Cross_validated_MSE_avg'})


%% Building regression model with optimal parameters


model = ratGEM;
model.b = model.b(:, 1);
model = generateRules(model);
model.genes = upper(model.genes);

    
flux_q = [];

kappa = 372.7594;
rho = 372.7594;
epsilon = 0.0036;

thresh_up = 1.008695652; 
thresh_down = 1 / thresh_up;


up_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 > thresh_up)
    };

dw_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 < thresh_down)
    };


parfor i = 1:length(up_q)
    
    flux_q(i, :) = constrain_flux_regulation_inconsistencies(model, ...
                                                  up_q{i}, dw_q{i}, kappa, rho, epsilon, 0, [], 1);
    
end


%% builds elastic net model


X_train = []; Y_train = [];
X_train = (flux_q);
Y_train = qds_flux;


[B, FitInfo] = lasso(X_train, Y_train, 'Alpha', 0.05928773, 'CV', 3);
    
idxLambdaMinMSE = FitInfo.IndexMinMSE
coef = B(:, idxLambdaMinMSE);
coef0 = FitInfo.Intercept(idxLambdaMinMSE);
    
yhat = X_train * coef + coef0;
    
lambda_min = FitInfo.LambdaMinMSE;

%% Random index k-fold, 10-fold cross validation

flux_q = [];

kappa = 1E3
rho = 1E3
epsilon = 1E-3

thresh_up = thresh; 
thresh_down = 1 / thresh_up;


up_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 > thresh_up), ...
    fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 > thresh_up)
    }

 dw_q = {fujimaki_19.Gene(fujimaki_19.Day3_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day3_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day3_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day4_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day6_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day8_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day10_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day12_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day14_3 ./ fujimaki_19.Day2_3 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_1 ./ fujimaki_19.Day2_1 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_2 ./ fujimaki_19.Day2_2 < thresh_down), ...
    fujimaki_19.Gene(fujimaki_19.Day16_3 ./ fujimaki_19.Day2_3 < thresh_down)
    }


    parfor i = 1:length(up_q)
    
        flux_q(i, :) = constrain_flux_regulation_inconsistencies(model, ...
                                                      up_q{i}, dw_q{i}, kappa, rho, epsilon, 0, [], 1);
        
    end


X_train = []; Y_train = [];
X_train = flux_q;
Y_train = qds_flux;

cv_idx = crossvalind('kfold', Y_train, 10)

X_test_predictions = zeros([length(Y_train) 1]);

for i = 1:10

    i
    idx_train = cv_idx ~= i;
    idx_test = cv_idx == i;

    X_train_subset = X_train(idx_train, :);
    Y_train_subset = Y_train(idx_train);

    X_test_subset = X_train(idx_test, :);
    Y_test_subset = Y_train(idx_test);

    % z-score normalize X_train and X_test
    X_train_subset = zscore(X_train_subset, 1);
    X_test_subset = zscore(X_test_subset, 1);


    % optimize alpha
    alpha_array = linspace(1E-4, 1, 100);

    mse_cv = [];
    num_coeff = [];


    parfor j = 1:length(alpha_array)
            
        B = []; FitInfo = [];
    
        [B, FitInfo] = lasso(X_train, Y_train, 'Alpha', alpha_array(j), 'CV', 3);
    
        idxLambdaMinMSE = FitInfo.IndexMinMSE;
        
        % finds crossfold mse
        mse_cv(j) = FitInfo.MSE(idxLambdaMinMSE)

    end


    [M, I] = min(mse_cv)
    
    min_alpha = alpha_array(I)


    % builds model with optimal parameters
    [B, FitInfo] = lasso(X_train_subset, Y_train_subset, 'Alpha', min_alpha, 'CV', 3);
    
    idxLambdaMinMSE = FitInfo.IndexMinMSE
    coef = B(:, idxLambdaMinMSE);
    coef0 = FitInfo.Intercept(idxLambdaMinMSE);
        
    lambda_min = FitInfo.LambdaMinMSE

    % applies model to data it's never seen before
    X_test_predictions(idx_test) = X_test_subset * coef + coef0;

end

%% results

scatter(Y_train, X_test_predictions)

[r, p] = corr(Y_train, X_test_predictions)

lr_model_scatter_t = table(Y_train, X_test_predictions, 'VariableNames', {'actual_qds', 'predicted_qds'})
